name: ConnectionGuard
version: '${version}'
author: gerolndnr
website: https://connectionguard.net
main: com.github.gerolndnr.connectionguard.spigot.ConnectionGuardSpigotPlugin
api-version: 1.13
folia-supported: true
softdepend:
  - LuckPerms
  - floodgate
permissions:
  connectionguard.command.cloud:
    default: op
  connectionguard.command.policy:
    default: op
  connectionguard.command.policy.activate:
    default: op
commands:
  connectionguard:
    name: connectionguard
    description: Retrieve information about connections ingame.
    aliases:
      - cg
