/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.github.johnrengelman.shadow").version("8.1.1")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // Cloud uses Gson on every native adapter; include it instead of relying on a server copy.
    implementation("com.google.code.gson:gson:2.11.0")
    // Safe, bounded competitor config reader, bundled on all three native adapters.
    implementation("org.yaml:snakeyaml:2.2")
    shadow("org.xerial:sqlite-jdbc:3.46.0.0")
    shadow("redis.clients:jedis:5.0.0")
    shadow("net.luckperms:api:5.4")

    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation("com.google.code.gson:gson:2.11.0")
    testImplementation("net.luckperms:api:5.4")
    testImplementation("org.xerial:sqlite-jdbc:3.46.0.0")
    testImplementation("redis.clients:jedis:5.0.0")
    testImplementation("com.h2database:h2:2.1.214")
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

// Compile the exact frozen 0.6.0 validator separately; never include it in production artifacts.
val legacyIntel060 = sourceSets.create("legacyIntel060") {
    compileClasspath += sourceSets.main.get().output + configurations.compileClasspath.get()
}

tasks.named<Test>("test") {
    dependsOn(tasks.named(legacyIntel060.classesTaskName))
    systemProperty("cg.legacyIntel060.classes", legacyIntel060.output.classesDirs.asPath)
    systemProperty("cg.legacyIntel060.source", file("src/legacyIntel060/java/com/github/gerolndnr/connectionguard/core/local/IntelSnapshot.java").absolutePath)
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    // Production Intel refresh is outside tests; fixtures use owned loopback transport.
    environment("CONNECTIONGUARD_INTEL_REFRESH", "false")
    // Changing the owned Redis fixture must not reuse a previous skipped/integration test report.
    inputs.property("redisFixturePort", providers.environmentVariable("CG_TEST_REDIS").orElse("disabled"))
}
