/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.github.johnrengelman.shadow").version("8.1.1")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    shadow("com.google.code.gson:gson:2.11.0")
    shadow("org.xerial:sqlite-jdbc:3.46.0.0")
    shadow("redis.clients:jedis:5.0.0")
    shadow("net.luckperms:api:5.4")

    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation("com.google.code.gson:gson:2.11.0")
    testImplementation("net.luckperms:api:5.4")
    testImplementation("org.xerial:sqlite-jdbc:3.46.0.0")
    testImplementation("redis.clients:jedis:5.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    // Changing the owned Redis fixture must not reuse a previous skipped/integration test report.
    inputs.property("redisFixturePort", providers.environmentVariable("CG_TEST_REDIS").orElse("disabled"))
}
